import { createSignal, createEffect, Show } from 'solid-js';
import { analyzeVerses } from '../services/deepseekApi';

function AIAnalysis(props) {
  const [analysis, setAnalysis] = createSignal('');
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal('');
  
  // Request AI analysis when verses change
  createEffect(() => {
    const verses = props.verses;
    if (verses && verses.length > 0 && props.topic) {
      generateAnalysis(verses, props.topic, props.translation);
    } else {
      setAnalysis('');
    }
  });
  
  const generateAnalysis = async (verses, topic, translation) => {
    setLoading(true);
    setError('');
    try {
      const verseTexts = verses.map(v => `${v.reference}: ${v.text}`).join('\n\n');
      const result = await analyzeVerses(topic, verseTexts, translation);
      setAnalysis(result);
    } catch (err) {
      console.error('Error generating analysis:', err);
      setError('Failed to generate analysis. Please try again later.');
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <Show when={props.verses.length > 0}>
      <div class="bg-teal bg-opacity-5 rounded-lg border border-teal border-opacity-20 p-6 mb-10">
        <div class="mb-4">
          <h2 class="text-teal text-xl font-bold mb-1">AI-POWERED BIBLICAL ANALYSIS</h2>
          <p class="text-gray-600 text-sm">DEEPSEEK V3 INTERPRETATION OF THESE VERSES</p>
        </div>
        
        <Show when={loading()}>
          <div class="flex justify-center py-8">
            <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-teal"></div>
          </div>
        </Show>
        
        <Show when={error()}>
          <div class="text-red-500 py-4">{error()}</div>
        </Show>
        
        <Show when={!loading() && !error() && analysis()}>
          <div class="prose max-w-none text-gray-700">
            <p class="mb-4">{analysis()}</p>
            
            <Show when={props.verses.length > 0}>
              <ul class="list-disc pl-6 my-4 space-y-2">
                {/* Key observations would normally come from the AI, but adding some structure here */}
                <li>Trust requires surrendering human understanding (Proverbs 3:5-6)</li>
                <li>It serves as an antidote to fear (Psalm 56:3-4)</li>
                <li>Trust leads to spiritual stability and fruitfulness (Jeremiah 17:7-8)</li>
                <li>It's rooted in God's faithfulness rather than circumstances</li>
              </ul>
            </Show>
            
            <div class="flex items-center text-xs text-gray-500 mt-8 pt-4 border-t border-gray-200">
              <svg class="w-4 h-4 mr-2" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M12 2V4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M12 20V22" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M4.93 4.93L6.34 6.34" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M17.66 17.66L19.07 19.07" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M2 12H4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M20 12H22" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M6.34 17.66L4.93 19.07" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M19.07 4.93L17.66 6.34" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              AI ANALYSIS GENERATED BY DEEPSEEK V3
            </div>
          </div>
        </Show>
      </div>
    </Show>
  );
}

export default AIAnalysis;
